czen/models.py
from django.db import models

class User(models.Model):
    """
    This is model for users
    """
    login = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    my_language = models.CharField(max_length=20)
    new_language = models.CharField(max_length=20)
    experience = models.IntegerField(default=0)


class Mluvi(models.Model):
    """
    This is model for language
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    my_word = models.CharField(max_length=25)
    new_word = models.CharField(max_length=25)
    status_word = models.IntegerField(default=0)

czen/forms.py
from django import forms
from .models import User
from django.forms import ModelForm


class UserForm(forms.Form):
    login = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput, max_length=20)


class Registration(forms.Form):
    login = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20)
    my_language = forms.CharField(max_length=20)
    new_language = forms.CharField(max_length=20)


class AddWord(forms.Form):
    my_word = forms.CharField(max_length=20)
    new_word = forms.CharField(max_length=20)


class EnterTranslate(forms.Form):
    translate_word = forms.CharField(max_length=20)

czen/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import User, Mluvi
from .forms import UserForm, Registration, AddWord, EnterTranslate
from .logika import verifications, added_word, word_learning, word_status, \
    word_repetition_check, word_repetition_status


def index(request):
    """
    Home page
    """
    return render(request, "index.html")


def registration_form(request):
    """
    This is function for registration new users
    """
    if request.method == "POST":
        login = request.POST.get('login')
        password = request.POST.get('password')
        my_language = request.POST.get('my_language')
        new_language = request.POST.get('new_language')
        registration_info = User.objects.create(
            login=login, password=password, my_language=my_language,
        new_language=new_language)
        registration_info.save()
        return HttpResponse(f"list{login}{password}{my_language}{new_language}")
    else:
        user_form = Registration()
        return render(request, "registration_form.html", {"form": user_form})


def enter_mluvik(request):
    """
    This is function for enter autorizated users to Mluvik
    """
    if request.method == "POST":
        login = request.POST.get('login')
        password = request.POST.get('password')
        User_registr = User.objects.get(login=login)
        word_verifications = verifications(login, password, User_registr.login,
                                           User_registr.password)
        if word_verifications == "verification":
            user_id = User_registr.id
            return redirect(f"../{user_id}/set_mluvik")
        else:
            return HttpResponse(f"Password Error")
    else:
        user_form = UserForm()
        return render(request, "enter_mluvik.html", {"form": user_form})


def set_mluvik(request, user_id):
    """
    Starting set Mluvik applications
    """
    id = User.objects.get(id=user_id)
    user_id = id.id
    experience = id.experience
    return render(request, "set_mluvik.html", {"user_name": id.login, "user_id": user_id,
                                               "experience": experience})


def mluvik(request, user_id):
    """
    Home page applications
    """
    id = User.objects.get(id=user_id)
    user_id = id.id
    experience = id.experience
    words_learn = word_learning(user_id)
    word_stat = word_repetition_status(user_id)
    if request.method == "POST":
        translate_word = request.POST.get('translate_word')
        if words_learn[0][1] == translate_word:
            oks = word_status(user_id, translate_word)
            return redirect(f"../../{user_id}/mluvik")
        else:
            return render(request, "clue_word.html", {"word_true": words_learn[0][1],
                "word_new": translate_word, "experience": experience})
    else:
        form = EnterTranslate()
        return render(request, "mluvik.html", {"user_name": id.login,
                "word_learn": words_learn[0][0], "form": form, "experience": experience,
                                               "user_id": user_id})


def add_word(request, user_id):
    """
    Page of the adding word to application Mluvik
    """
    id = User.objects.get(id=user_id)
    user_id = id.id
    experience = id.experience
    my_language = id.my_language
    new_language = id.new_language
    if request.method == "POST":
        new_word = request.POST.get('new_word')
        my_word = request.POST.get('my_word')
        check_word = word_repetition_check(user_id, my_word)
        if check_word == "No":
            word = added_word(my_word, new_word, user_id)
            return redirect(f"../../{user_id}/add_word")
        else:
            return HttpResponse(f"This word database is have")
    else:
        user_form = AddWord()
        return render(request, "add_word.html", {"user_name": id.login, "user_id": user_id,
            "form": user_form, "my_language": my_language, "new_language": new_language,
            "experience": experience})


def clue_word(request, user_id, my_word, new_word):
    """
    This function view if the entered word is not correct, it also gives a hint on how
    to correct it.
    """
    return render(request, "clue_word.html", {"user_id": user_id})

czen/templates/add_word.html
<!DOCTYPE html>
{% load static %}
<head>
  <meta charset="utf-8"/>
  <title>Mluvik add words</title>
  <link href="{% static "css/style.css" %}" rel="stylesheet"/>
</head>
<body class="wallpaper-image-theme">
  <h1 class="text-3-theme" style="left: 420px; right: 420px;">Add word to Mluvik</h1>
  <h2 class="text-2-theme" style="left: 320px; right: 520px; top: 105px;">Please input new word</h2>
  <h2 class="text-2-theme" style="left: 320px; right: 520px; top: 135px;">Please input translate word</h2>
  <h2 class="user-user">{{user_name}}</h2>
  <h2 class="user-experience">exp: {{experience}}</h2>
  <form method="POST">
    {% csrf_token %}
  <table class="red-table" style="color: rgb(24, 54, 105); width: 288px;">
    <tr><th><label for='id_my_word'>{{ my_language }}</label></th><td><input type='text' name='my_word' required id='id_my_word' /></td></tr>
    <tr><th><label for='id_new_language'>{{ new_language }}</label></th><td><input type='text' name='new_word' required id='id_new_word' /></td></tr>
  </table>
  <input type="submit" value="Send" class="green-button" style="font-size: 36px; position: absolute; left: 10px;
  right: 835px; top: 185px;">
  <button onclick="window.location.href='../../{{ user_id }}/set_mluvik'" type="button" class="button-home">Home</button>
  <button onclick="window.location.href='../../'" type="button" class="button-exit">Exit</button>
</form>
</body>
</html>

czen/templates/clue_word.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>Clue Word</title>
  <link href="{% static "css/style.css" %}" rel="stylesheet"/>
  <script>
  function clueWord() {
      var display = document.getElementById("display");
      display.innerHTML = 'Your word <span class="red-text">{{word_new}}</span> is failed, the correct word would be \
      <span class="green-text">{{word_true}}</span>';
    }
  </script>
</head>
<body class="wallpaper-image-theme">
  <h2 style="color: rgb(24, 54, 105); text-align: center; position: absolute; left: 10px; right: 900px; background-color: grey; border: 3px solid red; border-radius: 12px; font-size: 25px;">Yor word is failed</h2>
  <button onclick="clueWord()" class="green-button" style="left: 10px; right: 900px; top: 80px;">Clue word</button>
  <div id="display"></div>
  <button onclick="window.location.href='..{{ user_id }}/mluvik'" type="button" class="button-return">Return</button>"
  <h2 style="top: 220px;">user{{user_id}}</h2>
</body>
</html>

czen/templates/enter_mluvik.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>Enter Mluvik</title>
  <link href="{% static "css\style.css" %}" rel="stylesheet"/>
</head>
<body class="wallpaper-image-theme">
  <h1 class="text-1-theme" style="left: 340px; right: 340px;">Enter to Mluvik</h1>
  <h2 class="text-2-theme" style="left: 10px; right: 1000px;">Enter your Login</h2>
  <h2 class="text-2-theme" style="left: 10px; right: 1000px; top: 60px;">Enter your password</h2>
  <form method="POST">
    {% csrf_token %}
  <table class="red-table" style="top: 125px">
    {{ form }}
  </table><br>
  <input type="submit" value="Send" class="green-button" style="font-size: 36px; position: absolute; left: 10px;
  right: 845px; top: 200px;">
  <button onclick="window.location.href='../'" type="button" class="button-exit">Exit</button>
</form>
</body>
</html>

czen/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>Mluvik</title>
  <link href="{% static "css\style.css" %}" rel="stylesheet"/>
</head>
<body class="wallpaper-image-theme">
  <h1 class="text-1-theme" style="left: 350px; right: 350px;">Welcome to Mluvik</h1>
  <h2 class="text-1-theme" style="left: 450px; right: 450px; top: 100px;">WARNING</h2>
  <h3 class="text-2-theme" style="left: 320px; right: 320px; 320px; top: 200px;">
    Данное веб-приложение создано не для изучения языка, а только для расширения словарного запаса</h3>
  <button onclick="window.location.href='enter_mluvik'" type="button" class="green-button">Enter Mluvik</button>
  <button onclick="window.location.href='registration_form'" type="button" class="red-button">Registration</button>
</body>
</html>

czen/templates/mluvik.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>Mluvik</title>
  <link href="{% static "css/style.css" %}" rel="stylesheet"/>
</head>
<body class="wallpaper-image-theme">
  <h1 class="text-1-theme" style="left: 480px; right: 480px;">MLUVIK</h1>
  <h2 class="user-user">{{user_name}}</h2>
  <h2 class="user-experience">exp: {{experience}}</h2>
  <h2 class="text-2-theme" style="left: 160px; right: 780px; top: 110px;">{{ word_learn }}</h2>
  <form method="POST">
    {% csrf_token %}
  <table class="red-table" style="color: rgb(24, 54, 105); top: 160px;">
    {{ form }}
  </table>
  <input type="submit" value="Send" class="red-button" style="left: 160px; right: 780px; top: 205px;">
  <button onclick="window.location.href='../../{{user_id}}/set_mluvik'" type="button" class="button-home">Home</button>
  <button onclick="window.location.href='../../'" type="button" class="button-exit">Exit</button>
</form>
</body>
</html>

czen/templates/registration_form.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>Mluvik Registration Form</title>
  <link href="{% static "css\style.css" %}" rel="stylesheet"/>
</head>
<body class="wallpaper-image-theme">
  <h1 class="text-1-theme" style="left: 340px; right: 340px;">Registration to Mluvik</h1>
  <form method=POST>
    {% csrf_token %}
  <table class="red-table">
    {{ form }}
  </table>
  <input type="submit" value="Send" class="green-button" style="position: absolute; left: 10px; right: 800px; top: 250px;">
  <button onclick="window.location.href='../'" type="button" class="button-exit">Exit</button>
</form>
</body>
</html>

czen/templates/set_mluvik.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8"/>
  <title>Settings Mluvik</title>
  <link href="{% static "css/style.css" %}" rel="stylesheet"/>
</head>
<body class="wallpaper-image-theme">
  <h1 class="text-3-theme" style="left: 380px; right: 380px;">What do you choise today?</h1>
  <h2 class="user-user">{{user_name}}</h2>
  <h2 class="user-experience">exp: {{experience}}</h2>
  <button onclick="window.location.href='../../{{ user_id }}/mluvik'" type="button" class="green-button"
  style="left: 380px; right: 620px; top: 70px;">GO</button>
  <button onclick="window.location.href='../../{{ user_id }}/add_word'" type="button" class="red-button"
  style="left: 520px; right: 380px; top: 70px;">Add New Word</button>
  <button onclick="window.location.href='../../'" type="button" class="button-exit">Exit</button>
</body>
</html>